# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 02:34
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'AREA',
            },
        ),
        migrations.CreateModel(
            name='Consumibledanado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'CONSUMIBLEDANADO',
            },
        ),
        migrations.CreateModel(
            name='Consumibleusado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'CONSUMIBLEUSADO',
            },
        ),
        migrations.CreateModel(
            name='Docint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docint', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'DOCINT',
            },
        ),
        migrations.CreateModel(
            name='Dosismgy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bebe', models.FloatField()),
                ('nino', models.FloatField()),
                ('adulto', models.FloatField()),
                ('adultoobeso', models.FloatField()),
            ],
            options={
                'db_table': 'DOSISMGY',
            },
        ),
        migrations.CreateModel(
            name='Ecografia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('numinterno', models.IntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='radiologia.Area')),
                ('docint', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='radiologia.Docint')),
            ],
            options={
                'db_table': 'ECOGRAFIA',
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'ENTIDAD',
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaentrada', models.DateTimeField()),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'ENTRADA',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadsuma', models.IntegerField()),
            ],
            options={
                'db_table': 'INVENTARIO',
            },
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('lectura', models.IntegerField()),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'LECTURA',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.CharField(max_length=30)),
                ('detalle', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'PERMISO',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('identificacion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'PERSONA',
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesional', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'PROFESIONAL',
            },
        ),
        migrations.CreateModel(
            name='Radiologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('numinterno', models.IntegerField()),
                ('cantidadiopamidol', models.FloatField(blank=True, null=True)),
                ('kilovoltaje', models.FloatField()),
                ('miliamperaje', models.FloatField()),
                ('leido', models.BooleanField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='radiologia.Area')),
                ('docint', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='radiologia.Docint')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='radiologia.Entidad')),
            ],
            options={
                'db_table': 'RADIOLOGIA',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='radiologia.Permiso')),
            ],
            options={
                'db_table': 'ROL',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('servicio', models.CharField(blank=True, max_length=255, null=True)),
                ('insumo', models.BooleanField(default=0)),
                ('dosismgy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='radiologia.Dosismgy')),
            ],
            options={
                'db_table': 'SERVICIO',
            },
        ),
        migrations.CreateModel(
            name='Servicioeco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('servicio', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'SERVICIOECO',
            },
        ),
        migrations.CreateModel(
            name='Serviciopaciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='radiologia.Persona')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='radiologia.Servicio')),
            ],
            options={
                'db_table': 'SERVICIOPACIENTE',
            },
        ),
        migrations.CreateModel(
            name='Serviciopacienteeco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='radiologia.Persona')),
                ('servicioeco', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='radiologia.Servicioeco')),
            ],
            options={
                'db_table': 'SERVICIOPACIENTEECO',
            },
        ),
        migrations.CreateModel(
            name='Tipoconsumible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumible', models.CharField(max_length=8)),
                ('detalle', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TIPOCONSUMIBLE',
            },
        ),
        migrations.CreateModel(
            name='Tipoid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoid', models.CharField(max_length=2)),
                ('detalle', models.TextField()),
            ],
            options={
                'db_table': 'TIPOID',
            },
        ),
        migrations.CreateModel(
            name='Tipopaciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipopaciente', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'TIPOPACIENTE',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='rol',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='radiologia',
            name='serviciopaciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='radiologia.Serviciopaciente'),
        ),
        migrations.AddField(
            model_name='radiologia',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipoid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='radiologia.Tipoid'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipopaciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='radiologia.Tipopaciente'),
        ),
        migrations.AddField(
            model_name='lectura',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='radiologia.Profesional'),
        ),
        migrations.AddField(
            model_name='lectura',
            name='radiologia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='radiologia.Radiologia'),
        ),
        migrations.AddField(
            model_name='lectura',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventario',
            name='tipoconsumible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='radiologia.Tipoconsumible'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='tipoconsumible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='radiologia.Tipoconsumible'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ecografia',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='radiologia.Entidad'),
        ),
        migrations.AddField(
            model_name='ecografia',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='radiologia.Profesional'),
        ),
        migrations.AddField(
            model_name='ecografia',
            name='serviciopacienteeco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='radiologia.Serviciopacienteeco'),
        ),
        migrations.AddField(
            model_name='ecografia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumibleusado',
            name='radiologia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='radiologia.Radiologia'),
        ),
        migrations.AddField(
            model_name='consumibleusado',
            name='tipoconsumible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='radiologia.Tipoconsumible'),
        ),
        migrations.AddField(
            model_name='consumibledanado',
            name='radiologia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='radiologia.Radiologia'),
        ),
        migrations.AddField(
            model_name='consumibledanado',
            name='tipoconsumible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='radiologia.Tipoconsumible'),
        ),
        migrations.AddField(
            model_name='area',
            name='docint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='radiologia.Docint'),
        ),
    ]
