# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 14:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('radiologia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega_Placa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('persona_entrega', models.CharField(max_length=60)),
                ('identificacion', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('tipoid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='radiologia.Tipoid')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ENTREGA_PLACA',
            },
        ),
        migrations.CreateModel(
            name='Entrega_Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
            ],
            options={
                'db_table': 'ENTREGA_TURNO',
            },
        ),
        migrations.CreateModel(
            name='Lateralidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lateralidad', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'LATERALIDAD',
            },
        ),
        migrations.AddField(
            model_name='radiologia',
            name='archivo',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='radiologia',
            name='check',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='servicio',
            name='lateralidad',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='entrega_turno',
            name='radiologia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='radiologia.Radiologia'),
        ),
        migrations.AddField(
            model_name='entrega_turno',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviciopaciente',
            name='lateralidad',
            field=models.ForeignKey(default=-5, on_delete=django.db.models.deletion.DO_NOTHING, to='radiologia.Lateralidad'),
            preserve_default=False,
        ),
    ]
